delimiter $$

CREATE DEFINER=`root`@`192.168.1.8` PROCEDURE `fulladdr_by_kladr`(regcode INT, kladr_code VARCHAR(255))
SELECT DISTINCT
				l4.l7AOID AS aoid,
				CONCAT_WS(', ', CONCAT(l3.FORMALNAME, ' ', l3.SHORTNAME),
								CONCAT(l4FORMALNAME, ' ', l4SHORTNAME),
								CONCAT(l5FORMALNAME, ' ', l5SHORTNAME),
								CONCAT(l6FORMALNAME, ' ', l6SHORTNAME),
								CONCAT(l7FORMALNAME, ' ', l7SHORTNAME)) AS fullname,
				-- l3.ID as l3ID,
				l3.FORMALNAME AS l3FORMALNAME,
				-- l3.OFFNAME as l3OFFNAME,
				l3.SHORTNAME AS l3SHORTNAME,
				l3.AOLEVEL AS l3AOLEVEL,
				l3.CENTSTATUS AS l3CENTSTATUS,
				l3.AOID AS l3AOID,
				
				l4.*
FROM (SELECT
				l4.ID AS l4ID,
				l4.FORMALNAME AS l4FORMALNAME,
				-- l4.OFFNAME as l4OFFNAME,
				l4.SHORTNAME AS l4SHORTNAME,
				l4.AOGUID AS l4AOGUID,
				l4.AOLEVEL AS l4AOLEVEL,
				l4.CENTSTATUS AS l4CENTSTATUS,
				l4.AOID AS l4AOID,
				-- l4.PARENTGUID AS l4PARENTGUID,
				
				l5.*
FROM (SELECT
				l5.ID AS l5ID,
				l5.FORMALNAME AS l5FORMALNAME,
				-- l5.OFFNAME as l5OFFNAME,
				l5.SHORTNAME AS l5SHORTNAME,
				l5.AOGUID AS l5AOGUID,
				l5.PARENTGUID AS l5PARENTGUID,
				l5.AOLEVEL AS l5AOLEVEL,
				l5.CENTSTATUS AS l5CENTSTATUS,
				l5.AOID AS l5AOID,
				
				l6.*
FROM (SELECT
				l6.ID AS l6ID,
				l6.FORMALNAME AS l6FORMALNAME,
				-- l6.OFFNAME as l6OFFNAME,
				l6.SHORTNAME AS l6SHORTNAME,
				l6.AOGUID AS l6AOGUID,
				l6.PARENTGUID AS l6PARENTGUID,
				l6.AOLEVEL AS l6AOLEVEL,
				l6.CENTSTATUS AS l6CENTSTATUS,
				l6.AOID AS l6AOID,
				
				l7.*
FROM (SELECT
					ID AS l7ID,
					FORMALNAME AS l7FORMALNAME,
					-- OFFNAME as l7OFFNAME,
					SHORTNAME AS l7SHORTNAME,
					AOGUID AS l7AOGUID,
					PARENTGUID AS l7PARENTGUID,
					AOLEVEL AS l7AOLEVEL,
					CENTSTATUS AS l7CENTSTATUS,
					AOID AS l7AOID,
					IFNSUL AS l7IFNSUL
					-- LOCATE(UPPER(SHORTNAME), 'ГСК СНТ САД') AS PRIOR
				FROM
					AS_ADDROBJ -- USE INDEX (REGLEVFN)
				WHERE
				(
					LIVESTATUS = 1
					AND AOLEVEL IN (3,4,5,6, 7)
					# AND ( AOLEVEL IN (3,4,5,6) OR (AOLEVEL = 7 AND IFNSUL IS NULL) )
					#AND (FORMALNAME LIKE CONCAT(word, '%')) --  or FORMALNAME LIKE 'шлюз%'
					AND `CODE` = kladr_code
					#AND (FORMALNAME LIKE CONCAT('%', word, '%'))
					#AND match(OFFNAME) against ('+гск*' in boolean mode)
					AND REGIONCODE = regcode -- AND(a9.AOGUID<>@ParentGUID)
				)
-- limit 10
) l7
LEFT JOIN AS_ADDROBJ l6 	ON
					l6.ACTSTATUS = 1 AND l7.l7PARENTGUID = l6.AOGUID AND l6.REGIONCODE = regcode AND l6.ID<>l7.l7ID -- AND (a.AOGUID<>@ParentGUID)
) l6
LEFT JOIN AS_ADDROBJ l5 	ON
					l5.ACTSTATUS = 1 AND l6.l6PARENTGUID = l5.AOGUID AND l5.REGIONCODE = regcode AND l5.ID<>l6.l6ID -- AND (a.AOGUID<>@ParentGUID)
) l5
LEFT JOIN AS_ADDROBJ l4 	ON
					l4.ACTSTATUS = 1 AND l5.l5PARENTGUID = l4.AOGUID AND l4.REGIONCODE = regcode AND l4.ID<>l5.l5ID -- AND (a.AOGUID<>@ParentGUID)
) l4
LEFT JOIN AS_ADDROBJ l3 	ON
					l3.ACTSTATUS = 1 AND l4.l5PARENTGUID = l3.AOGUID AND l3.REGIONCODE = regcode AND l3.ID<>l4.l4ID -- AND (a.AOGUID<>@ParentGUID)$$

