=pod

=encoding utf8

Доброго всем

¡ ¡ ¡ ALL GLORY TO GLORIA ! ! !


=head1 Закачка и обновление ФИАС в базу Постгрес Postgresql

Закачиваются и обновляются только адреса со значением "ACTSTATUS"=1. Поэтому "AOGUID" уникален.

=head2 Создать схему и таблицу

  psql ... < tables.sql

=head2 Два режима запуска скрипта fias.pl

Для работы скрипта нужны зависимости - смотреть в начале скрипта. Модуль Model::Base выложен в этом репозитории. Модуль Mojo::Pg::Che хотел использовать для асинхронной вставки строк, не пошло, можно заменить DBI, но пусть будет.

=head3 Режим 1. Полное скачивание последней версии ФИАС XML

Перед запуском лучше пересоздать таблицу fias."AddressObjects", чтобы не мешали индексы, если были.

  cd <папка где скрипт>
  perl fias.pl --complete=1

Вариант полной загрузки, если предварительно архив скачан и распакован вручную. Нужен только файл AS_ADDROBJ_*.XML

  cd <папка где скрипт>
  perl fias.pl --xmlfile=AS_ADDROBJ_20140601_f78af112-09a4-4a17-9eb2-3c40f45e402e.XML

После полной закачки накатить индексы:

  psql ... < indexes.sql

=head3 Хранение версии

Версия сохраняется в той же таблице fias."AddressObjects"

  select * from fias."AddressObjects" where "AOGUID"='00000000-0000-0000-0000-000000000000';

=head3 Режим 2. Накатывание обновлений


  cd <папка где скрипт>
  perl fias.pl

Ставить эту команду в крон-сервис на ежедневный заход. Если сохраненная версия совпадет (нет обновления) - скрипт прервет работу.

=head3 Функции поиска адреса

  psql ... < functions.sql

Пример запуска:

  select *
  from fias.search_formalname('{\\mкрасный яр, \\mсамар}'::text[]) -- \m - начало слова
  order by
    weight desc,
    array_to_string("AOLEVEL", '')::int,
    array_to_string("FORMALNAME", '')
  ;

Возвращает массивы колонок для сбора полного адреса. При этом первые элементы "AOGUID"[1] и id[1] - уникальные идентификаторы найденного адреса.


=cut